spring.application.name=bookshelf


# in docker we use name of service instead of localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



security.jwt.secret-key=v3hB6lX9YwF7jC4tZmG8aD2rP5uO0iK1sE6qJ9kTmH4lYpXcWwS
# in millis
security.jwt.expiration-time=6000000
#
# Mail properties





spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=matejeliash@gmail.com
spring.mail.password=zaja hdnk rdfc vpjf


